version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: estibew_backend
    image: estibew_backend
    links:
      - db
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
      SERVER_PORT: 4000
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - "./:/src"
  # migration:
  #   image: estibew_backend
  #   links:
  #     - db
  #   command: sh -c "npx knex migrate:latest && npx knex seed:run"
  #   volumes:
  #     - "./:/src"

volumes:
  db:
    driver: local
